### ISSUE TITLE
Wrapper 만든 후, 변수 학습과 관련한 질문

### ISSUE THREAD

**Issue by LeeDoYup** [hccho2/RNN-Tutorial#1]
안녕하세요. 올려주시면 포스팅 잘 보았습니다.
포스팅된 방법으로 custom rnn 셀을 만들게 되면,
중간에 제가 추가적인 변수를 선언하여 연산하더라도 (call 함수에서)

이 후, 모델 학습시에 선언하고 사용한 변수들도 자동적으로 auto-grad를 통해 학습이 되나요?
(즉, 그냥 optimizer.minimize 를 사용하더라도 모두 학습이 될까요??)

**Comment by LeeDoYup** [comment]
제가 아직 하수라... 간단한 질문일 수 있지만 헷갈려서요 ㅠㅠ 감사합니다.

**Comment by hccho2** [comment]
네. 학습이 됩니다.

**Comment by LeeDoYup** [comment]
감사합니다
